[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "4c6544127838263017fe2d02d8b393aad391b462"
owners = ["Glyceri"]
	changelog = """
[2.3.0.14]
Fixes a quite common crash.
"""
