[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "f034287d98b967adbafc087ed7cd1412b2116b1c"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "Upgrade build target to net6"
