[plugin]
repository = "https://github.com/Styr1x/Browsingway.git"
commit = "8e182eb9140abb7806f4577171a4991f9ef32cb1"
owners = ["Styr1x"]
project_path = "Browsingway"
changelog = """\
- Bump Chromium to 126.0.6478.115
- Api X support
"""
