[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "772fb055ff0f90a7d6af72258fe09159602e8f97"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "- Update for 7.3 / API13"
