[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "a7538b7612ef6f57b13e18727236b0c504234f05"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "- Update for 7.3 / API13"
