[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "6a865b96532ec610d4942ee27cf1c032f3dc3c10"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "Update for APIv9"
