[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "eb71702266f49b16e1e82242375f3a24f9e3d942"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "Fixes an issue that prevented Sprint from activating"
