[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "b430f2661d099f484eaea8389e80902e1565f413"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "Fixes an issue that prevented Sprint from activating"
