[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "81575e7c288466396307c103ea87c86e846ea9a5"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "APIX / 7.0 Updates"
