[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "f8da634ac6984b4e6613474578f34ff32b1d506c"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "APIX / 7.0 Updates"
