[plugin]
repository = "https://github.com/cairthenn/Redirect.git"
commit = "e1659e329296b839173f0e0d3ec1ff466b4ffd51"
owners = [
    "cairthenn",
]
project_path = "Redirect"
changelog = "APIX / 7.0 Updates"
